services:

    ambta_doctrine_encrypt.orm_subscriber:
        class: Ambta\DoctrineEncryptBundle\Subscribers\DoctrineEncryptSubscriber
        tags:
            - { name: doctrine.event_subscriber }

    ambta_doctrine_encrypt.subscriber:
        alias: ambta_doctrine_encrypt.orm_subscriber

    ambta_doctrine_encrypt.encryptor:
        class: "%ambta_doctrine_encrypt.encryptor_class_name%"
        arguments:
            - "%ambta_doctrine_encrypt.secret_key_path%"

    ambta_doctrine_encrypt.command.decrypt.database:
        class: Ambta\DoctrineEncryptBundle\Command\DoctrineDecryptDatabaseCommand
        tags: [ 'console.command' ]
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@ambta_doctrine_encrypt.subscriber"

    ambta_doctrine_encrypt.command.encrypt.database:
        class: Ambta\DoctrineEncryptBundle\Command\DoctrineEncryptDatabaseCommand
        tags: [ 'console.command' ]
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@ambta_doctrine_encrypt.subscriber"

    ambta_doctrine_encrypt.command.encrypt.status:
        class: Ambta\DoctrineEncryptBundle\Command\DoctrineEncryptStatusCommand
        tags: [ 'console.command' ]
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@ambta_doctrine_encrypt.subscriber"