services:

    ambta_doctrine_encrypt.listener:
        class: Ambta\DoctrineEncryptBundle\EventListener\EntityEncryptDecryptListener
        arguments:
            - "@ambta_doctrine_encrypt.encryptor"
        tags:
            - { name: doctrine.event_listener, event: preUpdate }
            - { name: doctrine.event_listener, event: postLoad }
            - { name: doctrine.event_listener, event: postUpdate }
            - { name: doctrine.event_listener, event: preFlush }
            - { name: doctrine.event_listener, event: postFlush }
            - { name: doctrine.event_listener, event: onFlush }

    ambta_doctrine_encrypt.encryptor:
        class: "%ambta_doctrine_encrypt.encryptor_class_name%"
        arguments:
            - "%ambta_doctrine_encrypt.secret_key_path%"

    ambta_doctrine_encrypt.command.decrypt.database:
        class: Ambta\DoctrineEncryptBundle\Command\DoctrineDecryptDatabaseCommand
        tags: [ 'console.command' ]
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@ambta_doctrine_encrypt.listener"

    ambta_doctrine_encrypt.command.encrypt.database:
        class: Ambta\DoctrineEncryptBundle\Command\DoctrineEncryptDatabaseCommand
        tags: [ 'console.command' ]
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@ambta_doctrine_encrypt.listener"

    ambta_doctrine_encrypt.command.encrypt.status:
        class: Ambta\DoctrineEncryptBundle\Command\DoctrineEncryptStatusCommand
        tags: [ 'console.command' ]
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@ambta_doctrine_encrypt.listener"
